baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[params.author]
name = 'John Doe'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[taxonomies]
	category = 'categories'
	tag = 'tags'
	series = 'series'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        title = true
