name = 'chilldrak'
license = 'BSD-3-Clause'
licenselink = 'https://github.com/fedang/hugo-chilldark/LICENSE'
description = 'A simple black and white theme for Hugo'
homepage = 'https://github.com/fedang/hugo-chilldark'

[author]
  name = 'Federico Angelilli'
  homepage = 'fedang.net'
